# Generated by Django 4.2.4 on 2023-10-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='placeID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temple',
            name='temple_location',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
