# Generated by Django 4.2.2 on 2023-06-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.location'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='temple_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.location'),
        ),
    ]
