# Generated by Django 4.2.4 on 2023-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
