# Generated by Django 4.2.2 on 2023-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_event_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
