# Generated by Django 4.2.4 on 2023-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_temple_placeid_alter_temple_temple_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='lattitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='temple',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='temple',
            name='temple_location',
            field=models.CharField(max_length=200),
        ),
    ]
