# Generated by Django 4.2.4 on 2023-10-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_temple_lattitude_temple_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='lattitude',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='placeID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='temple',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temple',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temple',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temple',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
