# Generated by Django 4.2.2 on 2023-06-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_invitation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='name',
        ),
    ]
