# Generated by Django 4.2.2 on 2023-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_event_religious_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
