# Generated by Django 4.2.4 on 2023-10-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_event_city_event_country_event_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lattitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='temple',
            name='lattitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='temple',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
