# Generated by Django 4.2.4 on 2023-08-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_comment_commenter_alter_post_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='event',
            new_name='eventID',
        ),
        migrations.RenameField(
            model_name='templepost',
            old_name='temple',
            new_name='templeID',
        ),
    ]
