# Generated by Django 4.2.2 on 2023-06-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_event_end_date_time_event_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.location'),
        ),
    ]
