# Generated by Django 4.2.4 on 2023-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_event_lattitude_alter_event_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='placeID',
            field=models.CharField(max_length=200),
        ),
    ]
