# Generated by Django 4.2.2 on 2023-06-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_event_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(default='tamilnadu', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temple',
            name='temple_location',
            field=models.CharField(default='tamilnadu', max_length=200),
            preserve_default=False,
        ),
    ]
