# Generated by Django 4.2.2 on 2023-06-29 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_event_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invite_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='new post', max_length=200),
        ),
    ]
